# conda env create --file environment.yml
name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  {% if cookiecutter.project_packages == "All" -%}
  - python={{ cookiecutter.python_version }}
  - numpy
  - pandas
  - xlrd
  - matplotlib
  - seaborn
  - plotly
  - jupyter
  - jupyterlab
  - fs
  - pathlib
  - scikit-learn
  - pip
  {% endif -%}
  - pip:
    {% if cookiecutter.project_packages == "All" -%}
    - pyhere
    {% endif -%}