# conda env create --file environment.yml

name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  
  - python={{ cookiecutter.python_version }}
  - numpy=latest
  - pandas=latest
  - matplotlib=latest
  - seaborn=latest
  - plotly=latest
  - fs=latest
  - pathlib=latest
  - scikit-learn=latest
  - scipy=latest
  - jupyter=latest
  - jupyterlab=latest
  - keras=latest
  - tensorflow=latest
  - pytorch=latest
  - pip=latest

  - pip:
    - pyhere=latest