# conda env create --file environment.yml

name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  
  - python={{ cookiecutter.python_version }}
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - fs
  - pathlib
  - scikit-learn
  - scipy
  - jupyter
  - jupyterlab  
  - pyhere
  - keras
  - tensorflow
  - pytorch
  - pip