# conda env create --file environment.yml
name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  {% if cookiecutter.project_packages == "All" -%}
  - python={{ cookiecutter.python_version }}
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - fs
  - pathlib
  - scikit-learn
  - scipy
  - jupyter
  - jupyterlab  
  - jupyterlab-plotly
  - jupyterlab-kernelspy
  - jupyterlab-topbar
  - jupyterlab-theme-toggle
  - pip
  {% endif -%}
  - pip:
    {% if cookiecutter.project_packages == "All" -%}
    - pyhere
    - keras
    - tensorflow
    - pytorch
    {% endif -%}