name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python={{ cookiecutter.python_version }}
  - numpy
  - pandas
  {% if cookiecutter.project_packages == "All" -%}
  - pandas-flavor
  - pandas-profiling
  - pandas-openpyxl
  {% endif -%}
  - jupyter
  - jupyterlab
  {% if cookiecutter.project_packages == "All" -%}
  - keras
  - lightgbm
  {% endif -%}
  - matplotlib
  - seaborn
  {% if cookiecutter.project_packages == "All" -%}
  - missingno
  {% endif -%}
  - scipy
  - joblib
  - pip
  - plotly
  - pyjanitor
  - imbalanced-learn
  {% if cookiecutter.project_packages == "All" -%}
  - pylint
  {% endif -%}
  - pyprojroot
  {% if cookiecutter.project_packages == "All" -%}
  - pyspark
  {% endif -%}
  {% if cookiecutter.project_packages == "All" -%}
  - scikit-learn
  {% endif -%}
  {% if cookiecutter.project_packages == "All" -%}
  - statsmodels
  - tensorflow
  - category-encoders
  - yellowbrick
  - chart-studio
  - dvc
  - dvc[gdrive]
  - fastapi
  - uvicorn
  - gunicorn
  - pytest
  - httpx
  {% endif -%}
  
  
